id: I16E5A9D6
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-31T06:54:33.159922'
last_modified: '2022-05-31T06:54:33.159932'
parser: null
source_metadata:
  title: Rago Choktrul Tupten Shedrup Gyatso
  language: en
  description: 'Texts by and about Rago Choktrul Tupten Shedrup Gyatso (rag mgo mchog
    sprul thub bstan bshad sgrub rgya mtsho, 1879–1972), a prolific author of the
    Palyul tradition:'
  volume:
    f551E:
      title: 'Vines of Amṛta: A Prayer to the Lineage of the Bodhicaryāvatāra'
      base_file: f551E.txt
      order: 1
      parent: Lineage Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
